In [19]:
import torch
import cupy as cp
import numpy as np
import onnxruntime 


In [24]:
a = np.load('/home/wangnannan/workdir/AutoOrgan/cpu.npy')
b = np.load('/home/wangnannan/workdir/AutoOrgan/gpu.npy')

result = np.array_equal(a, b)
print(result)  # 输出: True
abs_diff_sum = np.sum(np.abs(a - b))

print("绝对值差之和:", abs_diff_sum)

False
绝对值差之和: 0.6221871010700684


In [ ]:
from pathlib import Path

# 设置文件夹路径
folder_a = Path("/home/wangnannan/workdir/AutoOrgan/cpu")
folder_b = Path("/home/wangnannan/workdir/AutoOrgan/gpu")

# 获取所有文件并排序（确保顺序一致）
files_a = sorted(folder_a.glob("*"))  # 可以指定后缀如 "*.txt"
files_b = sorted(folder_b.glob("*"))

# 确保数量一致
assert len(files_a) == len(files_b), "两个文件夹中的文件数量不一致"

# 配对
paired = list(zip(files_a, files_b))

# 打印结果
for f1, f2 in paired:
    a = np.load(f1)
    b = np.load(f2)

    result = np.array_equal(a, b)
    print(result)  # 输出: True
    abs_diff_sum = np.sum(np.abs(a - b))

    print("绝对值差之和:", abs_diff_sum)

In [1]:
import cupy as cp

x = cp.arange(24).reshape((2, 3, 4))

print("Shape:", x.shape)
print("Array:\n", x)

# 测试某个切片
print("x[0,1,2] =", x[0,1,2].item())  # 应该是 6
print("x[1,2,3] =", x[1,2,3].item())  # 应该是 23

Shape: (2, 3, 4)
Array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
x[0,1,2] = 6
x[1,2,3] = 23
